# Generated by Django 5.0.2 on 2025-11-12 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0004_remove_maestros_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestros',
            name='fecha_nacimiento',
        ),
    ]
