# Generated by Django 5.0.2 on 2025-11-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0005_remove_maestros_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestros',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
