# Generated by Django 5.0.2 on 2025-11-13 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0008_maestros_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='fecha_nacimiento',
        ),
    ]
