# Generated by Django 5.0.2 on 2025-11-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0009_remove_alumnos_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
