# Generated by Django 5.0.2 on 2025-12-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0010_alumnos_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_evento', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_realizacion', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_final', models.TimeField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=255, null=True)),
                ('publico_objetivo', models.CharField(blank=True, max_length=50, null=True)),
                ('programa_educativo', models.CharField(blank=True, max_length=255, null=True)),
                ('responsable_id', models.IntegerField(blank=True, null=True)),
                ('descripcion_breve', models.TextField(blank=True, null=True)),
                ('cupo_maximo', models.IntegerField(blank=True, default=0, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
